CREATE TABLE users (
	id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
	user_id VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	connecting boolean DEFAULT false,
	location geography(POINT, 4326),
	bio VARCHAR(250) DEFAULT '',
	profession VARCHAR(50) DEFAULT '',
	deviceCode VARCHAR(250)
);

CREATE TABLE interests (
	id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
	name VARCHAR(50) NOT NULL
);

INSERT INTO interests (name) VALUES
('Software Development'),
('Data Analysis'),
('Cybersecurity'),
('Cloud Computing'),
('Artificial Intelligence'),
('Digital Marketing'),
('Graphic Design'),
('UI/UX Design'),
('Project Management'),
('Product Management'),
('Human Resources'),
('Recruitment & Talent Acquisition'),
('Financial Analysis'),
('Accounting'),
('Investment Management'),
('Entrepreneurship'),
('Business Strategy'),
('Sales & Negotiation'),
('Customer Success'),
('Supply Chain Management'),
('Operations Management'),
('International Trade'),
('Public Relations'),
('Copywriting'),
('Technical Writing'),
('Translation & Localization'),
('Education & Training'),
('Instructional Design'),
('Research & Development'),
('Environmental Sustainability'),
('Renewable Energy'),
('Civil Engineering'),
('Mechanical Engineering'),
('Electrical Engineering'),
('Architecture'),
('Urban Planning'),
('Healthcare Management'),
('Public Health'),
('Nursing'),
('Pharmaceutical Research'),
('Biotechnology'),
('Psychology'),
('Human Behavior Research'),
('Law & Compliance'),
('Public Policy'),
('Government Administration'),
('Nonprofit Management'),
('Journalism'),
('Media Production'),
('Film & Video Production'),
('Music Production'),
('Event Planning'),
('Hospitality Management'),
('Tourism'),
('Culinary Arts'),
('Fashion Design'),
('Interior Design'),
('Real Estate'),
('Construction Management'),
('Logistics'),
('Quality Assurance'),
('Customer Experience Design'),
('Data Visualization'),
('Automation'),
('Blockchain Technology'),
('Agile Methodologies');

CREATE TABLE users_interests (
	user_id UUID NOT NULL,
	interest_id UUID NOT NULL,
	PRIMARY KEY (user_id, interest_id),
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (interest_id) REFERENCES interests(id)
);
